### PR TITLE
updating old packages and instructions for students

### PR DESCRIPTION
**Pull request by siddharthparmar7**
- Updated packages
- Updated instructions for students

#### Todo:
Please make suggestions/changes in this branch to give more detailed and clear instructions to the students.

`#makeLifeBetter`

### CODE REVIEW

**Comment by dannysmith** [comment]
Thanks so much for jumping on this! ❤️ 

Changes look sane to me, but I'd suggest getting a quick 👍 from a few other people who teach AppDev before merging - any thoughts @simistern ?

**First Question**: Do we need to update some *model solution* repo with identical changes, or at least add an issue to it referencing this PR? Same question for slides/exercises.

**Second question**: Is this intended to be a long-lived branch which others contribute to, is this still WIP, or are you asking for a final review before merging?

(If you want to merge, I'm 👍 once my first question is answered and at least one other AppDev instructor's given it the green light 🚀.)

Awesome job 👏 

***

### Also...

I'm afraid I've no idea what our conventions are for PRs/commits/labelling/issues/merges etc. But since such conventions *massively* improve communication & speed of comprehension, I tend to be a bit of a fanatic about them. So bearing that in mind...

1. This PR seems to introduce a bunch of small but unrelated changes. As someone who's not familiar with this repo, it'd be way easier to review if they weren't all in one commit. If *all* the code changes are a result of API changes in the dependencies, say so in the commit message so I'm not left guessing.

2. Your commit has the email `sidparmar@Sids-MacBook-Pro-2.local`, which is why it looks like a joint commit on GitHub and if we rebase/ff-merge into `master` it'll be hard to trace back to you.

3. I feel like we should use the [imperative](https://chris.beams.io/posts/git-commit/#imperative) for commit messages. 😜

4. Do we have any conventions or rules around reviews / who can merge what etc? If so where can I find them? If the answer is "In our collective brain" then we should definitely discuss on an issue in https://github.com/redacademy/lms.

PS. If this PR is still WIP and you intend to clean up before merging, ignore these points (and maybe add WIP to the title).

**Comment by dannysmith** [comment]
Also: I love `#makeLifeBetter`. Nicked.

**Comment by siddharthparmar7** [comment]
**Answer to the first question**: These change will only [React Router lesson](https://red-adp.herokuapp.com/lesson/03-react-router/) exercise 2. I will make an issue to change the instruction from `Add routes to your project in client/routes/Layout.js` to `Add routes to your project in client/routes/index.js`. 

The other change (coding) I made is to wrap the presentation components with `withStyle` instead of wrapping container components and passing classes as props to the presentation components. I can make an issue for that too. I just wanted to get approval from you and the other instructors for this. I don't know if we have a process of how are we going to make updates. I would love to talk to you all about this.

**Answer to the second question**: My intention with this branch was to ask for a review before merging. We used to have a convention of creating different branches to update repos with a branch name convention of `initials-feature/update/bugfix-cohort-year` ex: `sid-bugfix-spring19`. This convention got lost in time and with the expansion of the dev team. I would love to start working with dev team agreed conventions again so we can keep track of all the updates and bug fixes.

**Comment by dannysmith** [comment]
>  I would love to start working with dev team agreed conventions again so we can keep track of all the updates and bug fixes.

Just opened an issue on https://github.com/redacademy/LMS to discuss. I am a big fan of conventions :-P

**Pull request merged**
